### ISSUE TITLE
Can't install because husky tries to install git hooks

### ISSUE THREAD

**Issue by codemile** [RyoNkmr/eslint-plugin-atomic-design#163]
This library when installed runs `"postinstall": "husky install"` which fails because husky isn't installed. You shouldn't be running post install scripts for a published npm library. 

What I do is run a build script that creates a `dist` folder that contains everything to be published, and then inside that folder is placed a custom `package.json` file just for the published library. You can `cd ./dist && npm publish` from that folder.

**Comment by RyoNkmr** [comment]
Thank you for your report, I remove this line immediately
